version: '3'
services:
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: docker
    volumes: 
      - /docker/volumes/postgres:/var/lib/postgresql/data
    ports: 
      - '5432:5432'

    
    